#!/bin/sh

sysControl(){
LOCK_FILE="$HOME/.cache/eww-sysControl.lock"

run() {
    eww open --screen 1 sysControl
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    eww close sysControl
    rm "$LOCK_FILE"
fi
}

if [ "$1" = "sysControl" ]; then
sysControl
fi
