return {
  -- "ThePrimeagen/harpoon",
  -- branch = "harpoon2",
  -- -- event = 'VeryLazy',
  -- keys = {
  --   { '<leader>h', nil, desc = 'Harpoon' },
  -- },
  -- dependencies = { "nvim-lua/plenary.nvim" },
  -- config = function()
  --   local harpoon = require('harpoon')
  --   harpoon:setup({})
  --   WHICH_KEY.register({
  --     ['<leader>h'] = {
  --       name = 'Harpoon',
  --       h = { function() harpoon.ui:toggle_quick_menu(harpoon:list()) end, 'Show Harpoons' },
  --       c = { function() harpoon:list():append() end, 'Create Harpoon' },
  --       n = { function() harpoon:list():next() end, 'Next Harpoon' },
  --       p = { function() harpoon:list():prev() end, 'Prev Harpoon' },
  --       a = { function() harpoon:list():select(1) end, 'Harpoon 1' },
  --       r = { function() harpoon:list():select(2) end, 'Harpoon 2' },
  --       s = { function() harpoon:list():select(3) end, 'Harpoon 3' },
  --       t = { function() harpoon:list():select(4) end, 'Harpoon 4' },
  --     }
  --   })
  -- end
}
