-- require('noice').setup({
--   views = {
--     -- hover = {
--     --   size = {
--     --     width = '20%',
--     --     height = '30%'
--     --   },
--     --   relative = 'window'
--     -- }
--   },
--   lsp = {
--     override = {
--       ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
--       ['vim.lsp.util.stylize_markdown'] = true,
--       ['cmp.entry.get_documentation'] = true,
--     },
--
--     documentation = {
--       view = 'hover',
--       opts = {
--         lang = 'markdown',
--         replace = true,
--         render = 'plain',
--         format = { '{message}' },
--         win_options = { concealcursor = 'n', conceallevel = 3 },
--       },
--     },
--   },
--   markdown = {
--     hover = {
--       ['|(%S-)|'] = vim.cmd.help, -- vim help links
--       ['%[.-%]%((%S-)%)'] = require('noice.util').open, -- markdown links
--     },
--     highlights = {
--       ['|%S-|'] = '@text.reference',
--       ['@%S+'] = '@parameter',
--       ['^%s*(Parameters:)'] = '@text.title',
--       ['^%s*(Return:)'] = '@text.title',
--       ['^%s*(See also:)'] = '@text.title',
--       ['{%S-}'] = '@parameter',
--     },
--   },
--   presets = {
--     bottom_search = true,
--     command_palette = true,
--     long_message_to_split = true,
--     inc_rename = false,
--     lsp_doc_border = true,
--   },
-- })
